<a href="https://colab.research.google.com/github/marianagg0412/Analisis/blob/main/DLU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Sistemas de Ecuaciones Lineales**

In [1]:
import numpy as np
eps=np.finfo(float).eps #Esto es para encontrar el épsilon de la máquina

In [2]:
def DLU(A):
  filas = len(A)
  columnas = len(A[0]) #A una matriz rectangular la puedo descomponer de la forma D,L,U

  # Crea tres matrices llenas de ceros
  D = np.zeros((filas,columnas))
  L = np.zeros((filas,columnas))
  U = np.zeros((filas,columnas))

  # Copia cada elemento ij en la matriz correspondiente D,L,U
  for i in range(filas):
    for j in range(columnas):
      if i==j:
        D[i][j] = A[i][j]
      if i<j:
        U[i][j] = -1*A[i][j]
      if i>j:
        L[i][j] = -1*A[i][j]
  return(D,L,U)

In [3]:
def matriz_A():
  A = np.array([[-7,2,-1,1],[1,10,2,3],[2,2,-6,1],[1,2,1,-12]])
  return A

In [4]:
A = matriz_A()

In [5]:
DLU(A)

(array([[ -7.,   0.,   0.,   0.],
        [  0.,  10.,   0.,   0.],
        [  0.,   0.,  -6.,   0.],
        [  0.,   0.,   0., -12.]]),
 array([[ 0.,  0.,  0.,  0.],
        [-1.,  0.,  0.,  0.],
        [-2., -2.,  0.,  0.],
        [-1., -2., -1.,  0.]]),
 array([[ 0., -2.,  1., -1.],
        [ 0.,  0., -2., -3.],
        [ 0.,  0.,  0., -1.],
        [ 0.,  0.,  0.,  0.]]))

In [6]:
def vector_inicial():
  x0 = np.zeros((4,1))
  return x0

In [7]:
vector_inicial()

array([[0.],
       [0.],
       [0.],
       [0.]])

In [8]:
def vector_b():
  b = np.array([[1],[-2],[3],[-6]])
  return b

In [9]:
vector_b()

array([[ 1],
       [-2],
       [ 3],
       [-6]])

In [10]:
def jacobi(tolerancia, delta, Nmax): #Nmax will be 1000
  i = 0
  d = delta + 1
  error = tolerancia + 1

  A = matriz_A()
  b = vector_b()
  x0 = vector_inicial()
  B = DLU(A) #Evaluating coeficient matrix
  D = B[0]
  L = B[1]
  U = B[2]
  T = np.linalg.inv(D)@(L+U) #Jacobi method matrix
  C = np.linalg.inv(D)@(b) #Jacobi method vector

  while (error > tolerancia) and (delta < d) and (Nmax > i):
    i+=1
    print("Contador: ", i)
    x = T@x0 + C
    print("X ", x)
    d = np.linalg.norm(A@x - b)
    print("Delta: ", d)
    error = np.linalg.norm(x-x0)
    #error = np.linalg.norm(x-x0)/np.linalg.norm(x)
    print("Error: ", error) #Generally the error and the delta will not be the same.
    x0 = x
    print("-------------------------------------")

In [11]:
jacobi(eps,eps,1000)

Contador:  1
X  [[-0.14285714]
 [-0.2       ]
 [-0.5       ]
 [ 0.5       ]]
Delta:  1.2686969049913748
Error:  0.7486041432327945
-------------------------------------
Contador:  2
X  [[-0.05714286]
 [-0.23571429]
 [-0.53095238]
 [ 0.41309524]]
Delta:  0.26981296536893706
Error:  0.13089284360856598
-------------------------------------
Contador:  3
X  [[-0.07534014]
 [-0.21202381]
 [-0.52876984]
 [ 0.41170635]]
Delta:  0.057612368497863435
Error:  0.02998453124076368
-------------------------------------
Contador:  4
X  [[-0.06908163]
 [-0.21022392]
 [-0.52717026]
 [ 0.4143202 ]]
Delta:  0.028331460951455684
Error:  0.007197176119102716
-------------------------------------
Contador:  5
X  [[-0.06842248]
 [-0.21195385]
 [-0.52404849]
 [ 0.41527502]]
Delta:  0.01133885348066711
Error:  0.0037528992632314693
-------------------------------------
Contador:  6
X  [[-0.06922631]
 [-0.21293056]
 [-0.52424627]
 [ 0.41530178]]
Delta:  0.005046316741746248
Error:  0.0012806048538186508
------

In [12]:
def gauss(tolerancia, delta, Nmax): #Nmax will be 1000 , Gauss-Seidel
  i = 0
  d = delta + 1
  error = tolerancia + 1

  A = matriz_A()
  b = vector_b()
  x0 = vector_inicial()
  B = DLU(A) #Evaluating coeficient matrix
  D = B[0]
  L = B[1]
  U = B[2]
  T = np.linalg.inv(D-L)@(U) #Gauss-Seidel method matrix
  C = np.linalg.inv(D-L)@(b) #Gauss-Seidel method vector

  while (error > tolerancia) and (delta < d) and (Nmax > i):
    i+=1
    print("Contador: ", i)
    x = T@x0 + C
    print("X ", x)
    d = np.linalg.norm(A@x - b)
    print("Delta: ", d)
    error = np.linalg.norm(x-x0)
    #error = np.linalg.norm(x-x0)/np.linalg.norm(x)
    print("Error: ", error) #Generally the error and the delta will not be the same.
    x0 = x
    print("-------------------------------------")

In [13]:
gauss(eps,eps,1000)

Contador:  1
X  [[-0.14285714]
 [-0.18571429]
 [-0.60952381]
 [ 0.40634921]]
Delta:  0.7618584642018082
Error:  0.7691143679978424
-------------------------------------
Contador:  2
X  [[-0.05079365]
 [-0.19492063]
 [-0.51417989]
 [ 0.4204321 ]]
Delta:  0.25375696111496737
Error:  0.1336010235310666
-------------------------------------
Contador:  3
X  [[-0.06503275]
 [-0.21679038]
 [-0.52386903]
 [ 0.41479312]]
Delta:  0.0540775524025408
Error:  0.02840272780394973
-------------------------------------
Contador:  4
X  [[-0.07070266]
 [-0.21259387]
 [-0.52529999]
 [ 0.4149008 ]]
Delta:  0.010251604035409168
Error:  0.007198454265207006
-------------------------------------
Contador:  5
X  [[-0.06928385]
 [-0.21248186]
 [-0.52477177]
 [ 0.41508172]]
Delta:  0.0016141140121212476
Error:  0.0015288264465132483
-------------------------------------
Contador:  6
X  [[-0.06930146]
 [-0.21264002]
 [-0.52480021]
 [ 0.41505153]]
Delta:  0.0003518964473880891
Error:  0.00016445313713737628
-----