<a href="https://colab.research.google.com/github/marianagg0412/Analisis/blob/main/DLU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Sistemas de Ecuaciones Lineales**

In [3]:
import numpy as np
eps=np.finfo(float).eps #Esto es para encontrar el épsilon de la máquina

In [2]:
def DLU(A):
  filas = len(A)
  columnas = len(A[0]) #A una matriz rectangular la puedo descomponer de la forma D,L,U

  # Crea tres matrices llenas de ceros
  D = np.zeros((filas,columnas))
  L = np.zeros((filas,columnas))
  U = np.zeros((filas,columnas))

  # Copia cada elemento ij en la matriz correspondiente D,L,U
  for i in range(filas):
    for j in range(columnas):
      if i==j:
        D[i][j] = A[i][j]
      if i<j:
        U[i][j] = -1*A[i][j]
      if i>j:
        L[i][j] = -1*A[i][j]
  return(D,L,U)

In [14]:
def matriz_A():
  A = np.array([[-7,2,-1,1],[1,10,2,3],[2,2,-6,1],[1,2,1,-12]])
  return A

In [15]:
A = matriz_A()

In [8]:
DLU(A)

(array([[ -7.,   0.,   0.,   0.],
        [  0.,  10.,   0.,   0.],
        [  0.,   0.,  -6.,   0.],
        [  0.,   0.,   0., -12.]]),
 array([[ 0.,  0.,  0.,  0.],
        [-1.,  0.,  0.,  0.],
        [-2., -2.,  0.,  0.],
        [-1., -2., -1.,  0.]]),
 array([[ 0., -2.,  1., -1.],
        [ 0.,  0., -2., -3.],
        [ 0.,  0.,  0., -1.],
        [ 0.,  0.,  0.,  0.]]))

In [16]:
def vector_inicial():
  x0 = np.zeros((4,1))
  return x0

In [17]:
vector_inicial()

array([[0.],
       [0.],
       [0.],
       [0.]])

In [18]:
def vector_b():
  b = np.array([[1],[-2],[3],[-6]])
  return b

In [19]:
vector_b()

array([[ 1],
       [-2],
       [ 3],
       [-6]])